apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: codegen2-apr30-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/codegen2-apr30-1:9a77302ab5ca605e2d0b0a89746995025ae932ec@sha256:c988ed1a3398b7fd7003a22364b9cab0770ae21bd4f7e135bd3f48c44271b4ec # use pre-built to bootstrap
          name: app-inference
